version: '3.8'
services:
  redis:
    image: redis:6.2.1
    container_name: redis-db
  bot:
    build: ./bot
    volumes:
      - ./bot:/usr/proj
    restart: always
    depends_on:
      - redis
    container_name: bot
  listener:
    build: ./listener
    volumes:
      - ./listener:/usr/proj
    restart: always
    depends_on:
      - redis
      - bot
    ports:
      - "5000:5000"
    container_name: listener
